---
CableReady/ApplicationRecordEnableUpdates:
  Enabled: true
  Include:
    - "app/models/**/*.rb"

CableReady/BroadcasterControllerAction:
  Enabled: false
  Include:
    - "app/controllers/**/*.rb"

CableReady/UnusedCableReadyCall:
  Enabled: true
  Include:
    - "**/*.rb"
