name: Ruby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
       matrix:
         ruby-version: [2.6.8, 2.7.4, 3.0.4, 3.1.3, 3.2.1]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Lint
      run: bundle exec rubocop

    - name: Run tests
      run: bundle exec rspec spec
